language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - "12"

git:
  depth: 3

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  gitgub-token: $GITHUB_TOKEN
  local-dir: dist/
  target-brunch: gh-pages
  commit-message: "Deploy"
  on:
    branch: master