language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - "12"

git:
  depth: 3

script:
  - yarn build
notifications:
  email:
    recipients:
      - oscar@platzi.com
      - oscar@arepa.dev
    on_success: always
    on_failure: always
notifications:
slack: deploysgroup:0QL8zEfI4USBVac5VBfJbAhp
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  gitgub-token: $GITHUB_TOKEN
  local-dir: dist/
  target-brunch: gh-pages
  commit-message: "Deploy"
  on:
    branch: master